In [1]:
import torch

In [2]:
x = torch.empty(5,3)
print(x)

tensor([[3.9696e-33, 0.0000e+00, 3.9696e-33],
        [0.0000e+00, 3.9691e-33, 0.0000e+00],
        [3.9691e-33, 0.0000e+00, 3.9691e-33],
        [0.0000e+00, 3.9691e-33, 0.0000e+00],
        [3.9691e-33, 0.0000e+00, 3.9691e-33]])


In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.8774, 0.9624, 0.6991],
        [0.3681, 0.5225, 0.1710],
        [0.3715, 0.8162, 0.0894],
        [0.8212, 0.0853, 0.9143],
        [0.9948, 0.5611, 0.2451]])


In [7]:
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [13]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [16]:
x = x.new_ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [20]:
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[ 1.2770,  0.5571, -0.2910],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [21]:
print(x.size())

torch.Size([5, 3])


In [24]:
print(x.shape)

torch.Size([5, 3])


In [25]:
print(x)

tensor([[ 1.2770,  0.5571, -0.2910],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [28]:
y = torch.rand(5,3)
print(y)

tensor([[0.6727, 0.8396, 0.4724],
        [0.7977, 0.6705, 0.9163],
        [0.9188, 0.2571, 0.6282],
        [0.2792, 0.8982, 0.1539],
        [0.3011, 0.7270, 0.9746]])


In [29]:
x + y

tensor([[ 1.9497,  1.3967,  0.1814],
        [ 0.9361,  1.2670, -0.6110],
        [ 1.4205,  0.7533,  0.2941],
        [-0.8501,  0.8543, -0.0890],
        [ 1.7273,  1.0998,  0.3431]])

In [30]:
torch.add(x,y)

tensor([[ 1.9497,  1.3967,  0.1814],
        [ 0.9361,  1.2670, -0.6110],
        [ 1.4205,  0.7533,  0.2941],
        [-0.8501,  0.8543, -0.0890],
        [ 1.7273,  1.0998,  0.3431]])

In [32]:
result = torch.empty(5,3)
torch.add(x,y,out = result)

tensor([[ 1.9497,  1.3967,  0.1814],
        [ 0.9361,  1.2670, -0.6110],
        [ 1.4205,  0.7533,  0.2941],
        [-0.8501,  0.8543, -0.0890],
        [ 1.7273,  1.0998,  0.3431]])

In [33]:
print(result)

tensor([[ 1.9497,  1.3967,  0.1814],
        [ 0.9361,  1.2670, -0.6110],
        [ 1.4205,  0.7533,  0.2941],
        [-0.8501,  0.8543, -0.0890],
        [ 1.7273,  1.0998,  0.3431]])


In [34]:
y.add_(x)

tensor([[ 1.9497,  1.3967,  0.1814],
        [ 0.9361,  1.2670, -0.6110],
        [ 1.4205,  0.7533,  0.2941],
        [-0.8501,  0.8543, -0.0890],
        [ 1.7273,  1.0998,  0.3431]])

In [35]:
y = x[0,:]

In [36]:
y += 1

In [37]:
print(y)

tensor([2.2770, 1.5571, 0.7090])


In [38]:
print(x)

tensor([[ 2.2770,  1.5571,  0.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [39]:
print(x[0,:])

tensor([2.2770, 1.5571, 0.7090])


In [40]:
print(x[1])

tensor([ 0.1384,  0.5964, -1.5273])


In [41]:
print(x[:])

tensor([[ 2.2770,  1.5571,  0.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [42]:
print(x[0:])

tensor([[ 2.2770,  1.5571,  0.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [43]:
print(y)

tensor([2.2770, 1.5571, 0.7090])


In [44]:
y+=1

In [45]:
print(y)

tensor([3.2770, 2.5571, 1.7090])


In [46]:
print(x)

tensor([[ 3.2770,  2.5571,  1.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [47]:
print(x)

tensor([[ 3.2770,  2.5571,  1.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])


In [49]:
y = x.view(15)
print(y)

tensor([ 3.2770,  2.5571,  1.7090,  0.1384,  0.5964, -1.5273,  0.5017,  0.4962,
        -0.3341, -1.1293, -0.0439, -0.2429,  1.4262,  0.3727, -0.6315])


In [50]:
z = x.view(-1, 5)
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [51]:
print(z)

tensor([[ 3.2770,  2.5571,  1.7090,  0.1384,  0.5964],
        [-1.5273,  0.5017,  0.4962, -0.3341, -1.1293],
        [-0.0439, -0.2429,  1.4262,  0.3727, -0.6315]])


In [52]:
print(x)
print(y)
print(z)

tensor([[ 3.2770,  2.5571,  1.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])
tensor([ 3.2770,  2.5571,  1.7090,  0.1384,  0.5964, -1.5273,  0.5017,  0.4962,
        -0.3341, -1.1293, -0.0439, -0.2429,  1.4262,  0.3727, -0.6315])
tensor([[ 3.2770,  2.5571,  1.7090,  0.1384,  0.5964],
        [-1.5273,  0.5017,  0.4962, -0.3341, -1.1293],
        [-0.0439, -0.2429,  1.4262,  0.3727, -0.6315]])


In [53]:
x +=1

In [54]:
print(x)
print(y)
print(z)

tensor([[ 4.2770,  3.5571,  2.7090],
        [ 1.1384,  1.5964, -0.5273],
        [ 1.5017,  1.4962,  0.6659],
        [-0.1293,  0.9561,  0.7571],
        [ 2.4262,  1.3727,  0.3685]])
tensor([ 4.2770,  3.5571,  2.7090,  1.1384,  1.5964, -0.5273,  1.5017,  1.4962,
         0.6659, -0.1293,  0.9561,  0.7571,  2.4262,  1.3727,  0.3685])
tensor([[ 4.2770,  3.5571,  2.7090,  1.1384,  1.5964],
        [-0.5273,  1.5017,  1.4962,  0.6659, -0.1293],
        [ 0.9561,  0.7571,  2.4262,  1.3727,  0.3685]])


In [55]:
x_cp = x.clone().view(15)
print(x)
print(x_cp)
x -= 1
print(x)
print(x_cp)

tensor([[ 4.2770,  3.5571,  2.7090],
        [ 1.1384,  1.5964, -0.5273],
        [ 1.5017,  1.4962,  0.6659],
        [-0.1293,  0.9561,  0.7571],
        [ 2.4262,  1.3727,  0.3685]])
tensor([ 4.2770,  3.5571,  2.7090,  1.1384,  1.5964, -0.5273,  1.5017,  1.4962,
         0.6659, -0.1293,  0.9561,  0.7571,  2.4262,  1.3727,  0.3685])
tensor([[ 3.2770,  2.5571,  1.7090],
        [ 0.1384,  0.5964, -1.5273],
        [ 0.5017,  0.4962, -0.3341],
        [-1.1293, -0.0439, -0.2429],
        [ 1.4262,  0.3727, -0.6315]])
tensor([ 4.2770,  3.5571,  2.7090,  1.1384,  1.5964, -0.5273,  1.5017,  1.4962,
         0.6659, -0.1293,  0.9561,  0.7571,  2.4262,  1.3727,  0.3685])


In [56]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.1537])
-0.15368883311748505


In [57]:
torch.cuda.is_available()

False

In [58]:
x = torch.rand(5,3)

In [59]:
print(x)

tensor([[0.7907, 0.8170, 0.3709],
        [0.8535, 0.4522, 0.7386],
        [0.4580, 0.9732, 0.3583],
        [0.3657, 0.2233, 0.0035],
        [0.0668, 0.9032, 0.4775]])


In [60]:
x.trace()

tensor(1.6011)

In [61]:
x.diag()

tensor([0.7907, 0.4522, 0.3583])

In [62]:
x.triu()

tensor([[0.7907, 0.8170, 0.3709],
        [0.0000, 0.4522, 0.7386],
        [0.0000, 0.0000, 0.3583],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])

In [63]:
x.tril()

tensor([[0.7907, 0.0000, 0.0000],
        [0.8535, 0.4522, 0.0000],
        [0.4580, 0.9732, 0.3583],
        [0.3657, 0.2233, 0.0035],
        [0.0668, 0.9032, 0.4775]])

In [64]:
y = torch.rand(3, 5)

In [65]:
print(y)

tensor([[0.5232, 0.9597, 0.1657, 0.4076, 0.3095],
        [0.7109, 0.2686, 0.3080, 0.4267, 0.6192],
        [0.2825, 0.7044, 0.6055, 0.5832, 0.9463]])


In [66]:
x.mm(y)

tensor([[1.0993, 1.2395, 0.6072, 0.8873, 1.1016],
        [0.9767, 1.4608, 0.7280, 0.9717, 1.2431],
        [1.0327, 0.9532, 0.5926, 0.8109, 1.0834],
        [0.3511, 0.4134, 0.1315, 0.2464, 0.2547],
        [0.8119, 0.6431, 0.5784, 0.6912, 1.0318]])

In [67]:
y.mm(x)

tensor([[1.4784, 1.3932, 1.1115],
        [1.1298, 1.6565, 0.8696],
        [1.3784, 2.1235, 1.2959]])

In [68]:
print(y)

tensor([[0.5232, 0.9597, 0.1657, 0.4076, 0.3095],
        [0.7109, 0.2686, 0.3080, 0.4267, 0.6192],
        [0.2825, 0.7044, 0.6055, 0.5832, 0.9463]])


In [69]:
y.t

<function Tensor.t>

In [70]:
print(y.t)

<built-in method t of Tensor object at 0x0000000014E29C40>


In [71]:
z = y.t

In [72]:
print(z)

<built-in method t of Tensor object at 0x0000000014E29C40>


In [73]:
y.t()

tensor([[0.5232, 0.7109, 0.2825],
        [0.9597, 0.2686, 0.7044],
        [0.1657, 0.3080, 0.6055],
        [0.4076, 0.4267, 0.5832],
        [0.3095, 0.6192, 0.9463]])

In [74]:
print(y)

tensor([[0.5232, 0.9597, 0.1657, 0.4076, 0.3095],
        [0.7109, 0.2686, 0.3080, 0.4267, 0.6192],
        [0.2825, 0.7044, 0.6055, 0.5832, 0.9463]])


In [75]:
print(y.inverse())

RuntimeError: A must be batches of square matrices, but they are 5 by 3 matrices

In [76]:
z = x.mm(y)

In [77]:
print(z)

tensor([[1.0993, 1.2395, 0.6072, 0.8873, 1.1016],
        [0.9767, 1.4608, 0.7280, 0.9717, 1.2431],
        [1.0327, 0.9532, 0.5926, 0.8109, 1.0834],
        [0.3511, 0.4134, 0.1315, 0.2464, 0.2547],
        [0.8119, 0.6431, 0.5784, 0.6912, 1.0318]])


In [78]:
print(z.inverse())

tensor([[ -2042026.7500,    377442.1250,  -2511221.7500,   6158979.0000,
           2841567.0000],
        [ -3978656.7500,    973103.2500,   1268696.2500,   4632297.5000,
            599507.0000],
        [  5863542.0000,  -2087816.0000, -18815242.0000,  13436050.0000,
          12694156.0000],
        [ 18312332.0000,  -4334031.0000,  -2085617.3750, -25809408.0000,
          -5767027.5000],
        [-11467414.0000,   3170170.0000,  13130264.0000,   2023139.7500,
          -5862841.5000]])


In [79]:
x = torch.arange(1, 3)

In [80]:
print(x)

tensor([1, 2])


In [81]:
x.view(1, 2)

tensor([[1, 2]])

In [82]:
y = torch.arange(1, 4)
print(y)

tensor([1, 2, 3])


In [83]:
y.view(3,1)

tensor([[1],
        [2],
        [3]])

In [84]:
print(x + y)

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 0

In [85]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)

tensor([[1, 2]])


In [86]:
print(y)
print(x + y)

tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [90]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = x + y
print(id_before,id(y))

346296832 347068160


In [91]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id_before,id(y))

346822656 346822656


In [95]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out = y)
print(id_before,id(y))

338856320 338856320


In [96]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y += x
print(id_before,id(y))

116331008 116331008


In [97]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y.add_(x)
print(id_before,id(y))

345512512 345512512


In [98]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [99]:
a += 1
print(a, b)
b += 1
print(a, b)

tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [100]:
import numpy as np

In [101]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [102]:
a += 1
print(a, b)
b += 1
print(a, b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [103]:
c = torch.tensor(a)
print(c)
a += 1
print(a,c)

tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [108]:
device = torch.device('cpu')

In [109]:
y = torch.ones_like(x, device=device)
x = x.to(device)

In [110]:
z = x + y

In [111]:
print(z)

tensor([2, 3])


In [112]:
x

tensor([1, 2])

In [113]:
y

tensor([1, 1])

In [114]:
x = torch.ones(2, 2, requires_grad = True)

In [115]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [116]:
print(x.grad_fn)

None


In [117]:
y = x + 2

In [118]:
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [119]:
print(x.is_leaf, y.is_leaf)

True False


In [120]:
z = y * y *3

In [121]:
out = z.mean()

In [122]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [123]:
a = torch.randn(2, 2)

In [124]:
a = ((a * 3) / (a - 1))

In [125]:
print(a.requires_grad)

False


In [126]:
a.requires_grad_(True)

tensor([[ 5.3607e+00,  2.6988e-03],
        [ 1.2297e+00, -1.1598e+01]], requires_grad=True)

In [127]:
print(a.requires_grad)

True


In [128]:
b = (a * a).sum()

In [129]:
print(b.grad_fn)

In [130]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [131]:
print(x.grad)

None


In [132]:
out.backward()

In [133]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [134]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [135]:
out3 = x.sum()
x.grad.data.zero_()
out2.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])


In [136]:
x = torch.tensor([1.0, 2.0 , 3.0, 4.0], requires_grad = True)

In [137]:
y = 2 * x

In [138]:
z = y.view(2, 2)

In [139]:
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [140]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [164]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x**2
with torch.no_grad():
    y2 = x**3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [165]:
y3.backward()
print(x.grad)

tensor(2.)


In [159]:
y2.backward()
print(x.grad)

tensor(3.)


In [166]:
x = torch.ones(1,requires_grad = True)

In [167]:
print(x.data)
print(x.data.requires_grad)

tensor([1.])
False


In [168]:
y = 2 * x

In [169]:
x.data *= 100

In [170]:
print(x)

tensor([100.], requires_grad=True)


In [171]:
y.backward()

In [172]:
print(x)

tensor([100.], requires_grad=True)


In [173]:
print(x.grad)

tensor([2.])
